### ISSUE TITLE
Using icons in the vite project will result in an error

### ISSUE THREAD

**Issue by joker77877** [ant-design/ant-design-web3#1056]
## What happens?
Using icons in the vite project will result in an error.
![image](https://github.com/user-attachments/assets/aed83e7e-c8df-4d33-8f6a-ae8b680e69fc)
![image](https://github.com/user-attachments/assets/6e3e4765-7ee5-4cbc-908d-20ed57f7b07c)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by yutingzhao1991** [comment]
看上去只是一个警告，会影响项目运行吗？

**Comment by joker77877** [comment]
> 看上去只是一个警告，会影响项目运行吗？

不会但是为什么呢，一大串报错挺强迫症的

**Comment by yutingzhao1991** [comment]
> > 看上去只是一个警告，会影响项目运行吗？
> 
> 不会但是为什么呢，一大串报错挺强迫症的

嗯，我看看处理一下

**Comment by gin-lsl** [comment]
需要 babel-plugin-inline-react-svg 这个 plugin 修复，可以关注一下这个 pr： https://github.com/airbnb/babel-plugin-inline-react-svg/issues/126

**Comment by joker77877** [comment]
不理解 antd的 svg为什么不报错，这里还需要 plugin 修复

**Comment by NoahStepheno** [comment]
> 需要 babel-plugin-inline-react-svg 这个 plugin 修复，可以关注一下这个 Issue： [airbnb/babel-plugin-inline-react-svg#126](https://github.com/airbnb/babel-plugin-inline-react-svg/issues/126)

这个问题在 plugin 由于编译的问题，短时间不易处理。在调方倒是比较好处理，可以通过 hoc 的抹掉 defaultProps

`const ErasedSVGComponent = withEraseDefaultProps(SVGComponent);`
