### ISSUE TITLE
[Feature Request] 钱包为空时添加占位图

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#1060]
## Background

![image](https://github.com/user-attachments/assets/caaa102b-3bd8-49bf-b06f-8cc03d0adee6)

没有配置或者没有检测到任何钱包的情况下希望可以有一个占位图之类的。类似：
<img width="132" alt="image" src="https://github.com/user-attachments/assets/d16b4c3d-a899-411d-acba-dc1687ef50ca">

**Comment by coding-ice** [comment]
I want to try this feature.
