### ISSUE TITLE
[Bug] 未配置 EIP6963 的情况下无法检测到 MetaMask 的安装状态

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#1123]
## What happens?

![image](https://github.com/user-attachments/assets/9a8cbdbb-744a-4473-a725-69dc7ca6c095)

已经安装了钱包，但是这里是置灰的。看了一下：

```ts
    const hasExtensionInstalled = async () => {
      const provider = await injectedConnector?.getProvider?.();
      return !!provider;
    };
```

这个判断逻辑似乎不好使了，不知道是不是 wagmi 更新了。

## How To Reproduce

https://web3.ant.design/components/ethereum#support-switch-chains

**Comment by gin-lsl** [comment]
是插件加载的慢了吗？我这里是正常的。

**Comment by yutingzhao1991** [comment]
> 是插件加载的慢了吗？我这里是正常的。

<img width="506" alt="image" src="https://github.com/user-attachments/assets/30967c6d-ac81-4fec-b137-8bacb6b61bfc">

要看这个例子

**Comment by yutingzhao1991** [comment]
破案了，原因是因为安装了 TokenPocket 插件，抢占了 `window.ethereum`，所以项目中使用还是要打开 EIP6963.
