### ISSUE TITLE
Add scaffolding for umijs.

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#114]

**Comment by liangchaofei** [comment]
这个需求是什么？细说一下？

**Comment by yutingzhao1991** [comment]
> 这个需求是什么？细说一下？

新增一个包 `@ant-design/create-web3-umi` 和 `@ant-design/create-web3-nextjs` 这样的包，这样就可以用 `npm create @ant-design/web3-umi` 这样来创建一个脚手架了。

**Comment by yutingzhao1991** [comment]
想了一下，脚手架就不搞了吧，还是让用户直接使用 umijs 的官方脚手架，我们提供文档和教程让用户引入 antd web3 即可，不然后面维护也麻烦。

**Comment by haiifeng** [comment]
@yutingzhao1991 有具体的umijs接web3的文档嘛, 之前的umi3项目接wagmi,报provider错误

WagmiProviderNotFoundError: `useConfig` must be used within `WagmiProvider`.

![image](https://github.com/ant-design/ant-design-web3/assets/20502943/027b3004-37ac-4d6c-abc8-1e7bc07f8462)

**Comment by yutingzhao1991** [comment]
> @yutingzhao1991 有具体的umijs接web3的文档嘛, 之前的umi3项目接wagmi,报provider错误
> 
> WagmiProviderNotFoundError: `useConfig` must be used within `WagmiProvider`.
> 
> ![image](https://private-user-images.githubusercontent.com/20502943/326224207-027b3004-37ac-4d6c-abc8-1e7bc07f8462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTYzOTAsIm5iZiI6MTcxNDI5NjA5MCwicGF0aCI6Ii8yMDUwMjk0My8zMjYyMjQyMDctMDI3YjMwMDQtMzdhYy00ZDZjLWFiYzgtMWU3YmMwN2Y4NDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA5MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZTk3MjNjNjZlNTcxMDgzZDYxN2MyMWZjNGI4ZDA0NWE4MGZhMWU0MGU5MDgyMjU4YjQ5M2RjMzQ4NmJjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GvjaQT__cuRjTkeYKHBba8PP2_LfY8chpBERVndKPvk)

你怎么用的？最外面要包 `import { WagmiWeb3ConfigProvider } from '@ant-design/web3-wagmi';`
