### ISSUE TITLE
[Bug] Solana Balance incorrect

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#1244]
https://web3.ant.design/components/solana#recommended-configuration

<img width="943" alt="image" src="https://github.com/user-attachments/assets/447124b7-d69c-428a-8fe1-c8a82a122bfa">

**Comment by gin-lsl** [comment]
看下 https://api.mainnet-beta.solana.com/ 的请求，是不是被 403 了。可能需要换掉官方的 RPC。
