### ISSUE TITLE
Cannot find module 'packages/common/src'

### ISSUE THREAD

**Issue by cxp-13** [ant-design/ant-design-web3#1292]
## What happens?

我需要获取连接钱包的地址，按照给的演示代码。但是address属性不存在

## How To Reproduce
导入
`import { ConnectButton, Connector, useAccount  } from '@ant-design/web3';`
编写获取account
```
const { account } = useAccount();
```
控制台报错
![image](https://github.com/user-attachments/assets/6f6bc171-44f1-4e64-845a-f733b13a22b8)
源码报错：
![image](https://github.com/user-attachments/assets/a750306a-a8dc-4323-b3d9-3ba45cd234e6)

## Context

- **Ant Design Web3 Version**: "^1.18.1"
- **Node Version**:  v22.12.0
- **Platform**: window

**Comment by yutingzhao1991** [comment]
`account` 可能是 `undefined`，你试试改为 `account?.address` 看看。

**Comment by yutingzhao1991** [comment]
看了下，构建出来的 ts 类型确实有问题 `account: import("packages/common/src").Account | undefined;` 应该是 `account: import("@ant-design/web3-common").Account | undefined;` 才对。

你可以先 ignore 下这个类型的报错，我们修复一下发个新版本。

**Comment by yutingzhao1991** [comment]
应该和之前 https://github.com/ant-design/ant-design-web3/pull/1200 这个 PR 处理的问题是同一个

**Comment by yutingzhao1991** [comment]
试一下 1.19.0
