### ISSUE TITLE
Show avatar in ConnectButton

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#199]
Avatar should show in ConnectButton

<img width="696" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/13e4df40-64af-49eb-9621-46ce97e3e343">

**Comment by mahesh-gunjal** [comment]
![Screenshot from 2023-12-11 20-26-33](https://github.com/ant-design/ant-design-web3/assets/55346450/57d4b5a0-0808-43f2-b534-58dce64c25df)

Hi @yutingzhao1991 is this the desired feature ? please let me know.

**Comment by mahesh-gunjal** [comment]
@yutingzhao1991 can you assign this issue to me as I am not able to do it at my end. Thank you.

**Comment by mahesh-gunjal** [comment]
@yutingzhao1991 Do my assigned issue imply any specific access rights or permissions within the repository? I am facing permission denied error at my end.

**Comment by yutingzhao1991** [comment]
> @yutingzhao1991 Do my assigned issue imply any specific access rights or permissions within the repository? I am facing permission denied error at my end.

Issue and permissions are unrelated; you need to fork a copy of the code to your own repository to submit a PR.

<img width="689" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/9f078490-fea9-45bc-82d6-50222d5de332">
