### ISSUE TITLE
New officail website index page

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#210]
分为四个部分：

- [x] #211
- [x] #241
- [x] Custom theme
- [x] #242

**Comment by yutingzhao1991** [comment]
![web3官网](https://github.com/ant-design/ant-design-web3/assets/1061968/bda4043f-fb3a-4937-8ee3-08b0895447c4)

**Comment by li-jia-nan** [comment]
my task:

- Banner

**Comment by jrr997** [comment]
认领 Components show

**Comment by kiner-tang** [comment]
最近有点忙，领个简单的 Features 先
