### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#211]

**Comment by yutingzhao1991** [comment]
@li-jia-nan 这个你计划什么时候搞，因为下周一要发布，这周要搞完

**Comment by li-jia-nan** [comment]
> @li-jia-nan 这个你计划什么时候搞，因为下周一要发布，这周要搞完

我周三开始搞，算上周末，一共五天时间，搞得完

**Comment by yutingzhao1991** [comment]
> > @li-jia-nan 这个你计划什么时候搞，因为下周一要发布，这周要搞完
> 
> 我周三开始搞，算上周末，一共五天时间，搞得完

嗯，有空可以先提个 PR 把架子搭起来，这样其它人可以基于架子开发其它部分，不容易冲突

**Comment by li-jia-nan** [comment]
> 嗯，有空可以先提个 PR 把架子搭起来，这样其它人可以基于架子开发其它部分，不容易冲突

我今天晚上搞一下

**Comment by yutingzhao1991** [comment]
@li-jia-nan 这个什么进展了？明天看看能搞定吗？要给设计师看一看~~

**Comment by li-jia-nan** [comment]
> @li-jia-nan 这个什么进展了？明天看看能搞定吗？要给设计师看一看~~

还差一个字体的设计稿，需要设计师更新一下，在群里已经说过了，我晚些时候先把 pr 提交上来吧

**Comment by yutingzhao1991** [comment]
> > @li-jia-nan 这个什么进展了？明天看看能搞定吗？要给设计师看一看~~
> 
> 还差一个字体的设计稿，需要设计师更新一下，在群里已经说过了，我晚些时候先把 pr 提交上来吧

嗯，可以先用 https://mdn.alipayobjects.com/huamei_mutawc/afts/img/A*zaaqSqbOOrkAAAAAAAAAAAAADlrGAQ/original 这张图
