### ISSUE TITLE
BUG: Error occurred when importing components into a new project.

### ISSUE THREAD

**Issue by lesenelir** [ant-design/ant-design-web3#218]
### Introduction
When I create a new project and import components, an error occurs.

<img width="734" alt="Screenshot 2023-12-12 at 02 52 38" src="https://github.com/ant-design/ant-design-web3/assets/47740312/ad1dd7c3-4d2f-4761-817d-256e49705f4b">

### Steps to Reproduce
1. Create a new Vite project using `create vite`.
2. Copy the code from [this URL](https://web3.ant.design/components/wagmi#basic-usage) into the `App.tsx` file of the newly created Vite project.

Possible location of the issue: `/packages/web3/nft-card/NFTCard.tsx` lines 9, 10, 11.

**Comment by yutingzhao1991** [comment]
### Solution

install vite plugin `vite-plugin-svgr`, and then config it in vite config like this:

```ts
import { defineConfig } from "vite";
import svgr from "vite-plugin-svgr";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    svgr({
      svgrOptions: {
        exportType: "named",
      },
      include: ["**/*.svg"],
    }),
  ],
});

```

We will change the `exportType` of SVGR to the `default` to simplify the configuration, https://github.com/ant-design/ant-design-web3/issues/220

**Comment by yutingzhao1991** [comment]
The new version imports SVGs inline, so this issue no longer exists.

ref: https://github.com/ant-design/ant-design-web3/pull/265
