### ISSUE TITLE
update svgr config exportType to 'default'

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#220]
`import { ReactComponent as SVGComponent } from '../svgs/arbitrum-colorful.svg';`

to

`import SVGComponent from '../svgs/arbitrum-colorful.svg';`

**Comment by mahesh-gunjal** [comment]
@yutingzhao1991 please assign this issue to me.

**Comment by yutingzhao1991** [comment]
@mahesh-gunjal  I will work on it now.
