### ISSUE TITLE
Auto hide ConnectModal guide when window is too small, such like in mobile

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#268]
<img width="493" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/260b20b0-ca4f-4bae-aaf4-eed6959fb6d2">

**Comment by aditya-armal** [comment]
Can i do it?

**Comment by yutingzhao1991** [comment]
@aditya-armal Do you have time to deal with this issue?

**Comment by aditya-armal** [comment]
yes @yutingzhao1991, will work on it today.

**Comment by yutingzhao1991** [comment]
> yes @yutingzhao1991, will work on it today.

You can use `Grid.useBreakpoint` in `antd` for this issue. https://ant.design/components/grid-cn#components-grid-demo-usebreakpoint

**Comment by aditya-armal** [comment]
Can i have the installation file?

**Comment by yutingzhao1991** [comment]
> Can i have the installation file?

I don't understand. what installation file mean?

**Comment by aditya-armal** [comment]
i am getting this error while running it: Can't resolve '@ant-design/web3-icons'.

**Comment by yutingzhao1991** [comment]
> i am getting this error while running it: Can't resolve '@ant-design/web3-icons'.

Have you run 'pnpm i' and 'pnpm run dev' before run 'pnpm run dev:docs'?

**Comment by aditya-armal** [comment]
pnpm run dev

> @ant-design/web3-docs@0.0.0 dev C:\Users\Administrator\Documents\Github\ant-design-web3
> pnpm run --parallel --if-present --recursive --filter "@ant-design/*" dev

Scope: 5 of 6 workspace projects
packages/assets dev$ father dev
packages/common dev$ father dev
packages/web3 dev$ father dev
packages/icons dev$ FATHER_CACHE=none father dev
packages/wagmi dev$ father dev
packages/icons dev: 'FATHER_CACHE' is not recognized as an internal or external command,
packages/icons dev: operable program or batch file.
packages/icons dev: Failed
C:\Users\Administrator\Documents\Github\ant-design-web3\packages\icons:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @ant-design/web3-icons@0.1.0 dev: `FATHER_CACHE=none father dev`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
 
 @yutingzhao1991

**Comment by yutingzhao1991** [comment]
> FATHER_CACHE

You use windows?

It's looks like windows can not recognize env `FATHER_CACHE`, you can use  https://www.npmjs.com/package/cross-env for fix it.

**Comment by yutingzhao1991** [comment]
I incidentally fixed this issue in #320 

However, you can submit a PR to add support for Windows.
