### ISSUE TITLE
site: 官网组件展示模块需要适配暗色模式

### ISSUE THREAD

**Issue by kiner-tang** [ant-design/ant-design-web3#286]
<img width="1440" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/10286961/14b564dd-1bd6-4bf2-8814-084230c7480b">

**Comment by li-jia-nan** [comment]
banner 图片也需要一张可以适配暗色模式的

**Comment by yutingzhao1991** [comment]
> banner 图片也需要一张可以适配暗色模式的

我找设计师要一下，不过估计没那么好弄。可以有一个临时方案把图片调暗： `filter: brightness(0.2);` 

![image](https://github.com/ant-design/ant-design-web3/assets/1061968/fcd3b788-63e0-40af-9159-232552fef644)

**Comment by li-jia-nan** [comment]
> 可以有一个临时方案把图片调暗： `filter: brightness(0.2);`

这个效果看起来不太好呢
