### ISSUE TITLE
官网 Show Demos 设计走查修改

### ISSUE THREAD

**Issue by kiner-tang** [ant-design/ant-design-web3#294]

**Comment by kiner-tang** [comment]
@jrr997 你这边有时间跟进 show Demos 模块的 UI Debug 的问题吗？

**Comment by jrr997** [comment]
> @jrr997 你这边有时间跟进 show Demos 模块的 UI Debug 的问题吗？

@kiner-tang 可以的，现在还有啥问题需要跟进吗
