### ISSUE TITLE
RFC: NFTCard

### ISSUE THREAD

**Issue by RedJue** [ant-design/ant-design-web3#3]
## Summary

`NFTCard` component for web3 component library.

## API

| Property   | Description | Type | Default | 
| ---------- | ----------- | ------| ------| 
| actionText  | Text of action button | ReactNode | Buy Now
| image  |   NFTCard image   | ReactNode | -
| footer  | Footer of NFTCard | ReactNode | -
| isLike  | Whether like NFTCard | boolean | false
| likes  | Number of likes | number \| boolean | -
| price  |  Price of NFTCard   | number | -
| serialNumber  |   NFTCard serial number   | number | -
| showAction  | Whether to show action button | boolean \| ReactNode | false
| name  |   NFTCard name   | string | -
| type  |   NFTCard style type   | default \| pithy |  default
| onLikeChange  |  Callback executed when like button is changed   | ( isLike:boolean ) => void | -
| onActionChange  |  Callback executed when action button is changed   | ( ) => void | -
## Basic Example

```tsx
import { NFTCard } from '@ant-design/web3'

const Demo = () => (
  <NFTCard
   name="Demo NFT"
   image ={<img alt="example" src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png" />}
   showAction
   price={1.2}
   likes={9000}
   isLike
   serialNumber={404}
  />
);
```

**Comment by yutingzhao1991** [comment]
@RedJue 看看能不能参考 https://web3.ant.design/zh-CN/guide/contributing 这个拆分下任务，这样我可以拉更多人一起过来共建。

**Comment by RedJue** [comment]
好，我一会看看能不能拆分一下任务

**Comment by RedJue** [comment]
@yutingzhao1991 UI看能不能再和设计沟通一下，之前那版我看的时候还是有点问题的。

**Comment by yutingzhao1991** [comment]
> @yutingzhao1991 UI看能不能再和设计沟通一下，之前那版我看的时候还是有点问题的。

嗯，具体什么问题，可以列出来，我和设计师一起看看。

**Comment by RedJue** [comment]
1. 是否需要 NFTCard.group 这种形式，设计图里表达不明确
2. description 属性也需要加到基础的例子里，目前 UI 上没体现

**Comment by yutingzhao1991** [comment]
> 1. 是否需要 NFTCard.group 这种形式，设计图里表达不明确
> 2. description 属性也需要加到基础的例子里，目前 UI 上没体现

1. group 先不用做，感觉这部分需求不是特别通用，可以后面再观察。
1. description 这个我找设计师补充下，可以先跳过，应该是加在 name 下面。

**Comment by RedJue** [comment]
写的时候遇到几个问题，这边备注一下
1. 有几个 icon 用到了，引用方式上是按切图静态资源来引用还是基于在线的图床之类的来引
2. 暗黑模式需要单独暴露属性来控制还是直接响应 `antd` 的暗黑算法
3. footer 这块内容是我们有预设的还是完全让用户自定义

**Comment by yutingzhao1991** [comment]
> 写的时候遇到几个问题，这边备注一下
> 
> 1. 有几个 icon 用到了，引用方式上是按切图静态资源来引用还是基于在线的图床之类的来引
> 2. 暗黑模式需要单独暴露属性来控制还是直接响应 `antd` 的暗黑算法
> 3. footer 这块内容是我们有预设的还是完全让用户自定义

1. icon 具体是哪个？尽量用 antd 的 icon 或者我们 web3 的 icon，如果没有完全一样的类似的也行，可以和设计师协商一下。
2. 暗黑响应 antd 的就好了。
3. Footer 完全自定义吧，目前看没有什么明确的通用的内容。

**Comment by yutingzhao1991** [comment]
<img width="73" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/d946a5b8-c133-4e4a-9144-abd876bfa02c">

icon 是指这个吗？直接打包在组件里面吧，感觉还是不要有静态资源引用，避免出现网络请求。

**Comment by RedJue** [comment]
OK，那我直接放到组件里面吧
