### ISSUE TITLE
Chrome icon color bug

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#310]
<img width="240" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/54d7769a-24b3-44d0-870c-ddad3e3bd15c">

**Comment by gin-lsl** [comment]
看起来像是 svg babel 插件的问题

**Comment by yutingzhao1991** [comment]
> 看起来像是 svg babel 插件的问题

最开始是好的，很奇怪，有可能是 svg 不规范，直接打开是好的，但是放到网页中就有问题了。

**Comment by gin-lsl** [comment]
我看它这个 svg 在优化的时候，这些 id 会被重写，可能是跟其他的地方重复了（奇怪浏览器竟然不是取最接近的）。

![image](https://github.com/ant-design/ant-design-web3/assets/18319675/62744247-03e3-495f-9909-5ab0fe227428)


优化是通过 inline-react-svg babel 插件做的，然后底层用的是 svgo，2.8.0 版本。

https://github.com/svg/svgo/pull/1784 这个 pr 似乎是在修复这个问题，不过那个 babel 插件用的版本比较老……

不知道能不能通过配置绕过，感觉有点麻烦。

**Comment by gin-lsl** [comment]
之前没问题是只有一个这种渐变色，直到最近，又加了一个 polygon 的渐变彩色图标……

**Comment by yutingzhao1991** [comment]
<img width="784" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/04c7ab6a-55c9-49d0-a6d2-7c57c2cf9d44">

发现这个图标在 ConnectModal 里面的时候又正常了。

**Comment by yutingzhao1991** [comment]
> 之前没问题是只有一个这种渐变色，直到最近，又加了一个 polygon 的渐变彩色图标……

哦哦。明白了，所以是和 polygon 同时出现的时候会有这个问题。
