### ISSUE TITLE
Components name `CryptoPrice` is not correct

### ISSUE THREAD

**Issue by lxhyl** [ant-design/ant-design-web3#372]
* The component `CryptoPrice` only display token's amount by `props.value`. NOT price! So the name is not correct.

   [CryptoPrice](https://github.com/ant-design/ant-design-web3/blob/348398dff4c2a30edd055fdb24b01dc4807e47c3/packages/web3/src/crypto-price/index.tsx#L36-L44)

* Default token's metadata is IMPORTANT. Must be required not option. options may be confusing.    

    [CryptoPriceProps](https://github.com/ant-design/ant-design-web3/blob/348398dff4c2a30edd055fdb24b01dc4807e47c3/packages/web3/src/crypto-price/index.tsx#L9-L17)

**Comment by yutingzhao1991** [comment]
Thank you for your suggestion.

The `symbol` and `decimals` can be obtained from the context, with Ethereum being the default. However, if developers have configured their own chain, the system will prioritize the developer's configuration. The component is intended for developers' use, and they should be able to ensure that they have configured the correct chain. I believe this design is reliable.

[Get chain config from React context](https://github.com/ant-design/ant-design-web3/blob/348398dff4c2a30edd055fdb24b01dc4807e47c3/packages/web3/src/crypto-price/index.tsx#L24)

**Comment by lxhyl** [comment]
Thanks for the explanation.  I thought this component is use for any token amount. (ERC20, ERC1155). Only for native token(ETH)?

**Comment by yutingzhao1991** [comment]
It can be used with other tokens, but by default, it's for ETH. If you want to use it for other tokens, you need to configure the symbol and decimals.

But, you've reminded me that we can support built-in popular ERC20 token support in the future, like this:


```ts
import { USDT, CryptoPrice } from '@ant-design/web3';
 
<CryptoPrice type={USDT} value={10000n} />
```

or 


```ts
import { CryptoPrice } from '@ant-design/web3';

<CryptoPrice type="usdt" value={10000n} />
```

**Comment by lxhyl** [comment]
It's weird to use it like this. If user give `Symbol = USDT`, but forget giving `decimal = 6`. The current implementation will miscalculate `value`. So i still think token's metadata should be required not option.  UI Library giving default value maybe have misunderstanding.

And back to my first question, component name should be `CryptoAmount` not price. There not have price logic .

**Comment by yutingzhao1991** [comment]
Yes, after the user sets the USDT, it should by default include the decimal, and there's no need for the user to configure it again.

As for the component name being CryptoPrice, it's because it was originally designed to display asset prices, but indeed, CryptoAmount is a better name. We can consider adding a new name, CryptoAmount, in future versions and gradually phase out CryptoPrice.
