### ISSUE TITLE
头部视觉问题

### ISSUE THREAD

**Issue by restartgr** [ant-design/ant-design-web3#379]
<img width="899" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/101981882/a84c4da4-db74-49c6-a9b4-91043f2b2573">
因为icon和按钮没有背景色导致某些宽度后面的背景图会“遮盖”

**Comment by yutingzhao1991** [comment]
感觉移动端应该单独出一个简单一点的图，我找下设计师。
