### ISSUE TITLE
 ConnectButton: 当 size 为 small 时，头像太大了

### ISSUE THREAD

**Issue by kiner-tang** [ant-design/ant-design-web3#386]
<img width="862" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/10286961/81040ee0-ac94-4ca2-ac54-e022c36ad03e">

当 size 为 small 时，头像太大了，看起来太挤了，一点间距都没有

**Comment by yutingzhao1991** [comment]
要不要这样改我再和设计师对一下吧。当前 small 这个效果其实也不算是问题，因为 antd Button 的 small 和 default 的文字的大小和行高是一样的，只是 padding 没了，这个头像继承了这样的样式，所以是这个效果。

<img width="580" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/111c073c-8e29-4d95-b369-80a9ed88d3eb">

<img width="375" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/7ea9596c-125a-41bd-9480-66e7c9290b30">

**Comment by kiner-tang** [comment]
> 要不要这样改我再和设计师对一下吧。当前 small 这个效果其实也不算是问题，因为 antd Button 的 small 和 default 的文字的大小和行高是一样的，只是 padding 没了，这个头像继承了这样的样式，所以是这个效果。
> 
> <img alt="image" width="580" src="https://private-user-images.githubusercontent.com/1061968/292652100-111c073c-8e29-4d95-b369-80a9ed88d3eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzODQ3MzEsIm5iZiI6MTcwMzM4NDQzMSwicGF0aCI6Ii8xMDYxOTY4LzI5MjY1MjEwMC0xMTFjMDczYy04ZTI5LTRkOTUtYjM2OS04MGE5ZWQ4OGQzZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMDIyMDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZmNzcxY2Q0MWNmMTExZWJkNDk2NzU5ZTQ0OWVlNzAwNWM3NmQzYzUxNzllNTNhNjkyYTIzODlhYWE2ZTkxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VzFbYqsiKYhe1VWRsIjgVxQtG3zOJYgAFA8BOeLU4pc"> <img alt="image" width="375" src="https://private-user-images.githubusercontent.com/1061968/292652104-7ea9596c-125a-41bd-9480-66e7c9290b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzODQ3MzEsIm5iZiI6MTcwMzM4NDQzMSwicGF0aCI6Ii8xMDYxOTY4LzI5MjY1MjEwNC03ZWE5NTk2Yy0xMjVhLTQxYmQtOTQ4MC02NmU3YzkyOTBiMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMDIyMDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI4YTJhYWVlYjk5MzBlZWM1YjcwOWQ5OTgwOWU2MDMzNGZlNmM2YjllNzBiZTBkYzhhMTA5N2Q0YzZhNmIyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZuCDcPjuFV3nqinHVFk4XZOQ_4VVB3xbLbGx1MFmtsA">
> small 和 default 都是 22px

好，那周一跟设计同学对一下再看看要不要改，怎么改

**Comment by kiner-tang** [comment]
@yutingzhao1991 这个上次跟设计师对了吗？最终咋样

**Comment by yutingzhao1991** [comment]
> @yutingzhao1991 这个上次跟设计师对了吗？最终咋样

设计师说要改的，不过现在 PR 里面修改的方式会影响整个按钮原本的高度。这个问题感觉还好，可以等下周设计师按照 antd 的默认风格出新的设计稿后整体走查的时候再处理。
