### ISSUE TITLE
Support Bitcoin chain

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#395]
Bitcoin is important, and for Ant Design Web3, which supports multiple chains, it should support Bitcoin.

**Comment by yutingzhao1991** [comment]
@AmAzing129 看看出一个设计？下周三社区会议上讨论下，如果没有问题就可以开发了

**Comment by AmAzing129** [comment]
**What wallets**

Here are the most popular bitcoin wallets for browser:

- Unisat: famous for inscribing BRC-20 and supports ARC-20.

- Xverse: Ordinals/Taproot address and payment address.

- Leather(former name Hiro): for STAMPS.

- OKX: renowned for the mobile app and its web3 wallets.

**Why Xverse**

imo, Xverse will likely be the first wallet to support:

- it will support runes protocol, launching at halving.

- its developer ecosystem, eg: [sats-connect](https://github.com/secretkeylabs/sats-connect).

**How to do**

These wallets above has different APIs. Drawing from the implementation of web3-solana, there is a [Bitcoin-Wallet-Standard](https://github.com/ExodusMovement/bitcoin-wallet-standard?tab=readme-ov-file) we can use. 

Our task is wrapping existing API with a Wallet Standard compatible API. Here is the example of [Sats Connect](https://github.com/ExodusMovement/bitcoin-wallet-standard/tree/master/packages/wallets/sats-connect) with an outdated version.

Pros:

- Some dapps such as MagicEden, will detect wallets automatically.

- Adheres to the "Wallets - Adapter - Provider" architecture model.

Cons:

The standard has not been widely adopted, and there remains substantial work to be done.

Any feedback or advice? I plan to give a demo this week to see if it works.
