### ISSUE TITLE
Support more wallet

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#399]
Such like: TokenPocket, ImToken etc...

**Comment by Likang0122** [comment]
Does it mean creating more in this folder 
```
/packages/assets/src/wallets
```

**Comment by yutingzhao1991** [comment]
> Does it mean creating more in this folder 
> ```
> /packages/assets/src/wallets
> ```

and packages/wagmi/src/wallets

**Comment by yutingzhao1991** [comment]
`/packages/assets/src/wallets` directory contains the fundamental information about wallets, and it includes wallet information for any blockchain.

`packages/wagmi/src/wallets` directory contains the WalletFactory that has been adapted for Ethereum, based on wagmi, and is used to construct a [Wallet](https://web3.ant.design/components/types#wallet).

You can start by adding the basic information in `/packages/assets/src/wallets`. As for the implementation of WalletFactory in wagmi, it needs to be thought through carefully.

---

`/packages/assets/src/wallets` 这个里面是钱包的基础信息，不管什么链的钱包信息都写在里面。

`packages/wagmi/src/wallets` 这个里面是适配以太坊后基于 wagmi 扩展的 WalletFactory，用于构造出 [Wallet](https://web3.ant.design/components/types#wallet)。

可以先补充 `/packages/assets/src/wallets` 里面的基础信息，至于 wagmi 中的 WalletFactory 如何实现还要再好好想一下。

**Comment by Likang0122** [comment]
https://github.com/ant-design/ant-design-web3/issues/399#issuecomment-1869837134

**Comment by Likang0122** [comment]
我来收集这些信息吧，TP, ImToken, OKX

**Comment by yutingzhao1991** [comment]
For support more wallet with WalletConnect, I have a idea about it: https://github.com/ant-design/ant-design-web3/issues/414
