### ISSUE TITLE
New component CryotoPay

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#415]
I think perhaps we should add a cryptocurrency payment component, which is a useful feature in many scenarios.

**Comment by yutingzhao1991** [comment]
![image](https://github.com/ant-design/ant-design-web3/assets/1061968/b308b81f-cd25-49f0-8747-d9fed8b30c32)

![image](https://github.com/ant-design/ant-design-web3/assets/1061968/028972e5-da9e-404d-9c43-bb57fd7d9f3d)

![image](https://github.com/ant-design/ant-design-web3/assets/1061968/c2ff4f54-1b97-4f70-a58e-f08f45a86b38)

**Comment by yutingzhao1991** [comment]
Discussions: https://github.com/ant-design/ant-design-web3/discussions/620

**Comment by Likang0122** [comment]
#876
