### ISSUE TITLE
Web3ConfigProvider should inherit the props from the parent Web3ConfigProvider

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#417]
Dealing with the following common situations:

```tsx
<Web3ConfigProvider locale={{
  ConnectButton: {
    connect: 'Connect'
  }
}}>
  <Web3ConfigProvider>
    <ConnectButton />
  </Web3ConfigProvider>
</Web3ConfigProvider>
```

**Comment by kiner-tang** [comment]
> ```ts
> <Web3ConfigProvider locale={{
>   ConnectButton: {
>     connect: 'Connect'
>   }
> }}>
>   <Web3ConfigProvider extendsContextFromParent>
>     <ConnectButton />
>   </Web3ConfigProvider>
> </Web3ConfigProvider>
> ```
> 
> Add a `extendsContextFromParent` props for it.

Why add the extendsContextFromParent property, shouldn't providers naturally support automatic nested configuration merging

**Comment by yutingzhao1991** [comment]
> > ```ts
> > <Web3ConfigProvider locale={{
> >   ConnectButton: {
> >     connect: 'Connect'
> >   }
> > }}>
> >   <Web3ConfigProvider extendsContextFromParent>
> >     <ConnectButton />
> >   </Web3ConfigProvider>
> > </Web3ConfigProvider>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add a `extendsContextFromParent` props for it.
> 
> Why add the extendsContextFromParent property, shouldn't providers naturally support automatic nested configuration merging

There are many attributes related to blockchain involved, and I'm concerned that merging by default could cause confusion. But after giving it more thought, perhaps not merging could lead to even more confusion.

So, let's go with the default merge. However, perhaps we can add an `extendsContextFromParent=false` to support cases where users do not want to merge.

---

涉及到很多区块链相关的属性，担心默认合并会带来误导。不过仔细想了想，也许不合并会带来更多误导。

那还是默认合并吧，不过或许可以加一个 `extendsContextFromParent=false` 来支持用户不希望合并的情况。

**Comment by cong1223** [comment]
> > ```ts
> > <Web3ConfigProvider locale={{
> >   ConnectButton: {
> >     connect: 'Connect'
> >   }
> > }}>
> >   <Web3ConfigProvider extendsContextFromParent>
> >     <ConnectButton />
> >   </Web3ConfigProvider>
> > </Web3ConfigProvider>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add a `extendsContextFromParent` props for it.
> 
> Why add the extendsContextFromParent property, shouldn't providers naturally support automatic nested configuration merging

I totally agree with you, props extendsContextFromParent is confusing.
