### ISSUE TITLE
Add a new adapter to BitcoinSV

### ISSUE THREAD

**Issue by dnh33** [ant-design/ant-design-web3#426]
Bitcoin is BSV

**Comment by yutingzhao1991** [comment]
Do you want to come and implement this adapter? Or share more of your thoughts.

**Comment by dnh33** [comment]
gm, yes I'm open to work on adding the new BSV adapter but it will have to wait till after the 8th of Janurary as I'm going on vacation

**Comment by AmAzing129** [comment]
Considering we have implemented the Bitcoin adatper, it's may not good to add other "fork version" of Bitcoin as we are a neutral library.
