### ISSUE TITLE
site: bitcoin icon color display unexpected when hover

### ISSUE THREAD

**Issue by kiner-tang** [ant-design/ant-design-web3#444]
expected:

![image](https://github.com/ant-design/ant-design-web3/assets/10286961/d721ca22-b015-4019-9e07-1f94aadc0f9e)

unexpected:

![image](https://github.com/ant-design/ant-design-web3/assets/10286961/4ce7e33a-eaf6-4812-9e9f-08769246754a)

**Comment by yutingzhao1991** [comment]
and this one:
<img width="239" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/b4908787-e167-49b9-9b88-f7f2128cbf3c">

**Comment by cong1223** [comment]
I noticed this issue today and have already fixed it locally.

**Comment by thinkasany** [comment]
> I noticed this issue today and have already fixed it locally.

好嘞，如果你已经写好了，还是你来pr吧，下次可以assign一下自己或者评论一下，不然容易做重复了。

我看到 ```fill="none" 好像表示不填充任何颜色```，去掉`fill="none"`, 似乎解决了这个问题。

<img width="834" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/117748716/284b5fdf-1a7e-4d43-b4a1-3ee1705bd102">

**Comment by cong1223** [comment]
这个USDTFIlled其实是个circle图形，我得把他替换掉

**Comment by cong1223** [comment]
点错了，我好像没法分配给自己

**Comment by thinkasany** [comment]
> 点错了，我好像没法分配给自己

那下次可以先评论一下，估计他们看到了会指给你

**Comment by kiner-tang** [comment]
如果想要领取任务，可以先评论回复一下，避免大家做了重复工作。
