### ISSUE TITLE
Clicking on the MetaMask for Chrome option does not directly launch the MetaMask Popup

### ISSUE THREAD

**Issue by cong1223** [ant-design/ant-design-web3#451]
当我点击第一个选项时我的理解是应该直接唤起插件去connect wallet，现在的情况是跳出去到metamask的chrome store了，不太确定是不是符合预期
<img width="774" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/37927942/7ecd60f6-b495-441b-96ac-3e3315c10024">

**Comment by yutingzhao1991** [comment]
你是在哪个 Demo 里面点击的？试试 https://web3.ant.design/components/wagmi 这里的。

你点击的可能是纯 UI 展示的 Demo。

看来这里有误导，感觉要加一点描述说明下。
