### ISSUE TITLE
Support skip to guide in simple mode

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#456]
<img width="392" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/8a722dde-c7bb-4593-b972-2cdbc17c9931">

**Comment by shanchuan1** [comment]
i can carry

**Comment by yutingzhao1991** [comment]
https://www.figma.com/file/uA5FgofzOVulGceri7SGpW/web3%E6%96%B0%E8%AE%BE%E8%AE%A1%E7%A8%BF?type=design&node-id=0%3A6995&mode=design&t=1Cz6HQy8hDJPdGIY-1

@shanchuan1 设计稿来了：

![image](https://github.com/ant-design/ant-design-web3/assets/1061968/d381c13c-b5fb-4218-a5a5-941d1b9b8909)

这样，footer 和 guide 分开
