### ISSUE TITLE
unexpected QRCode after disconnect

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#457]
Reproduction steps:

- Open ConnectModal http://localhost:8000/components/wagmi#add-more-wallets
- Click WalletConnect
- Click MetaMask for connect
- Disconnect
- Open ConnectModal

https://github.com/ant-design/ant-design-web3/assets/1061968/3cd7e7b8-6a5a-4e3b-9e5e-14dd6ad45ea1

Expected result: Return to the initial position after disconnection, do not display the QR code.

**Comment by thinkasany** [comment]
可以用`destroyOnClose`  在ConnectModal关闭时销毁 Modal 里的子元素么？这样子的话，每次重新打开也是初始化的，不会显示二维码。

**Comment by yutingzhao1991** [comment]
> 可以用`destroyOnClose` 在ConnectModal关闭时销毁 Modal 里的子元素么？这样子的话，每次重新打开也是初始化的，不会显示二维码。

这样感觉比较暴力，不太好。应该是在连接成功或者断开连接后把 modal 的内部页面路由重新定位到初始位置。
