### ISSUE TITLE
unexpected loading after back from GetWallet Panel

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#468]
Reproduction steps:

- Open ConnectModal https://web3.ant.design/components/wagmi#add-more-wallets
- Click WalletConnect
- Click `Get` button
- Click back arrow

https://github.com/ant-design/ant-design-web3/assets/1061968/c659e9c4-db83-4ca5-8357-5b35dc45b59f

**Comment by yutingzhao1991** [comment]
看上去应该是 WalletConnect 实现的 `getQrCode` 这个方法有问题，二维码的信息应该缓存一下。

**Comment by Likang0122** [comment]
这里tokenPocket的injected似乎这样才是正确的
``` typescript
    injected({
      target() {
        return {
          id: 'tokenPocket',
          name: 'tokenPocket',
          // @ts-ignore
          provider: window.tokenpocket,
        };
      },
    }),
```
![image](https://github.com/ant-design/ant-design-web3/assets/21904785/87101203-6f70-46a6-b4df-6be668f13f3c)

**Comment by Likang0122** [comment]
我现在看到的似乎是这样，浏览器插件钱包大多都支持`window.ethereum`，但是如果存在多个，要指定某个钱包就要用其独有的，比如`window.tokenpocket`，`window.safeheron` 等。

**Comment by yutingzhao1991** [comment]
> 这里tokenPocket的injected似乎这样才是正确的
> 
> ```ts
>     injected({
>       target() {
>         return {
>           id: 'tokenPocket',
>           name: 'tokenPocket',
>           // @ts-ignore
>           provider: window.tokenpocket,
>         };
>       },
>     }),
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/21904785/296448861-87101203-6f70-46a6-b4df-6be668f13f3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODYxNTIsIm5iZiI6MTcwNTI4NTg1MiwicGF0aCI6Ii8yMTkwNDc4NS8yOTY0NDg4NjEtODcxMDEyMDMtNmY3MC00NmE2LWI0ZGYtNmJlNjY4ZjEzZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAyMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzkwMmQyNjFhOTViZjgwZmEwZGI1YTAxYjhlZTRkZTE2ZmY1MDllZDMyMTdhOTc0YjA4OThlOWJhY2QyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.218m-GBpaZaTkO_YwVsqM89n-qXOO-oPPdAlmaHa4lE)

wagmi 默认不是用的 `window.tokenpocket`？

那感觉 wagmi 的实现不够好。按道理 `injected({ target: 'tokenPocket' })` 就应该直接用 `window.tokenpocket` 才对，不然配置这个 target 就没啥意义了。
