### ISSUE TITLE
ERR! Module parse failed: Unexpected token (31:26)

### ISSUE THREAD

**Issue by Osub** [ant-design/ant-design-web3#469]
ERR! Module parse failed: Unexpected token (31:26)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! | export function isReadable(color1, color2, wcag2 = { level: 'AA', size: 'small' }) {
ERR! |     const readabilityLevel = readability(color1, color2);
ERR! >     switch ((wcag2.level ?? 'AA') + (wcag2.size ?? 'small')) {
ERR! |         case 'AAsmall':
ERR! |         case 'AAAlarge':

**Comment by kiner-tang** [comment]
这个报错具体是怎么出现的呢？可以提供一下详细的复现路径吗？

**Comment by Osub** [comment]
加入 到  lowcode 物料组件中时报错的，应该是 不支持新语法 ??

**Comment by kiner-tang** [comment]
感觉这个应该在你们的业务系统中加上 babel 插件支持一下？或者是需要 `@ctrl/tinycolor` 这个库在生成的产物中编译一下。
