### ISSUE TITLE
ConnectButton message错误

### ISSUE THREAD

**Issue by shanchuan1** [ant-design/ant-design-web3#487]
复制成功的是tooltip的title文案，message却是地址   自定义title应该不等效与地址把 提示问题
<img width="835" alt="Snipaste_2024-01-12_16-53-56" src="https://github.com/ant-design/ant-design-web3/assets/102506618/94526eed-9a93-4222-9e3e-d79706496da2">
<img width="807" alt="Snipaste_2024-01-12_16-54-23" src="https://github.com/ant-design/ant-design-web3/assets/102506618/71cdcf42-86c4-460a-9664-184942a05d34">

**Comment by thinkasany** [comment]
话说这个复制成功提示是不是也可以作为一个配置项，默认的话保留这个，但是也许用户需要点其他自定义的提示。

**Comment by yutingzhao1991** [comment]
提示是有一点问题。

感觉可以改为 Address 的这种效果，就不用 message 提示了：

<img width="378" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/de916984-14e8-4387-a877-778afd82f1ab">

**Comment by thinkasany** [comment]
> 提示是有一点问题。
> 
> 感觉可以改为 [Address](https://web3.ant.design/zh-CN/components/address) 的这种效果，就不用 message 提示了：
> 
> <img alt="image" width="378" src="https://private-user-images.githubusercontent.com/1061968/296191221-de916984-14e8-4387-a877-778afd82f1ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTIwODQsIm5iZiI6MTcwNTA1MTc4NCwicGF0aCI6Ii8xMDYxOTY4LzI5NjE5MTIyMS1kZTkxNjk4NC0xNGU4LTQzODctYTg3Ny03NzhhZmQ4MmYxYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDkyOTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY2NTI2MzI3OTUyNzdhNDUyNGRjOTc0NzU1YzVjMDZkNjY5MWQ2NmVjY2YxMWVmMTc0MjBiYjFjNmU5YmVkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XgpcGNX93ZxbECCZgIfBpnM8hlnVPl_uInVV5WVFlLU">

@shanchuan1 你方便来个pr么？

**Comment by shanchuan1** [comment]
i try 一 try

**Comment by shanchuan1** [comment]
> 感觉可以改为 [Address](https://web3.ant.design/zh-CN/components/address) 的这种效果，就不用 message 提示了：

但是button的交互确实感觉message会好一点，毕竟在层级，样式深，message比较直观

**Comment by shanchuan1** [comment]
@yutingzhao1991 大佬这个改造一下吗

**Comment by yutingzhao1991** [comment]
> @yutingzhao1991 大佬这个改造一下吗

那就按照我上面说的，这种样式就统一改为复制成功后打一个对勾就好了。和 Address 保持一致。

或者如果要最简单的方式就是把 `复制地址成功` 改为 `复制成功`
