### ISSUE TITLE
Can not be used in nextjs

### ISSUE THREAD

**Issue by andy00614** [ant-design/ant-design-web3#494]
it will be noticed that `can't resolve 'lodash/merge'`, in the Next.js  
<img width="1177" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/28584664/f9670c37-5166-4f23-a7c5-23c46a898972">

**Comment by yutingzhao1991** [comment]
I will take a look at this issue

**Comment by andy00614** [comment]
I change the dependencies position, I have try, it better to me, please have a look

**Comment by yutingzhao1991** [comment]
@andy00614 try 1.3.1
