### ISSUE TITLE
Local environment development @ tanstack/react query dependency error

### ISSUE THREAD

**Issue by shanchuan1** [ant-design/ant-design-web3#501]
![image](https://github.com/ant-design/ant-design-web3/assets/102506618/1e849ec7-b31f-497a-8f4e-4870f51b0b19)
window环境 ，node  v16.17.1 ，chrome v120.0.6099.217

**Comment by yutingzhao1991** [comment]
https://github.com/ant-design/ant-design-web3/blob/main/packages/wagmi/src/wagmi-provider/index.tsx#L41 可能是这里的问题

**Comment by yutingzhao1991** [comment]
所有涉及到 wagmi 的 demo 都有这个问题吗？还是只有个别 demo 有问题？

**Comment by shanchuan1** [comment]
> 所有涉及到 wagmi 的 demo 都有这个问题吗？还是只有个别 demo 有问题？

 所有用到WagmiWeb3ConfigProvider这个组件的demo都会有这个问题，初步判断是@tanstack/react-query库5.17.0版本存在问题

**Comment by shanchuan1** [comment]
问题定位到了，wagmi的api: useConnect调用@tanstack/react-query的api: useMutation 参数存在差异，
![image](https://github.com/ant-design/ant-design-web3/assets/102506618/3e585e08-6b43-402a-b61e-f0d978b2c714)
![image](https://github.com/ant-design/ant-design-web3/assets/102506618/33e80d0b-d945-4ba2-878a-fe40efd096dd)
@yutingzhao1991

**Comment by yutingzhao1991** [comment]
> 问题定位到了，wagmi的api: useConnect调用@tanstack/react-query的api: useMutation 参数存在差异， ![image](https://private-user-images.githubusercontent.com/102506618/297687431-3e585e08-6b43-402a-b61e-f0d978b2c714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQ3NjAsIm5iZiI6MTcwNTYzNDQ2MCwicGF0aCI6Ii8xMDI1MDY2MTgvMjk3Njg3NDMxLTNlNTg1ZTA4LTZiNDMtNDAyYS1iNjFlLWYwZDk3OGIyYzcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMzIxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzZiYjBkMzUwMDVmODhmYzRjMmExMTM1ODA5MDc2NWRjYjkzMWI5YmVhYTZmNjc0OGM5NjE2OTNmYWEwYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4YsKy7p0FjPIrQ7Canvssk-cbHsRo6-Fihk2zfU3U_s) ![image](https://private-user-images.githubusercontent.com/102506618/297687558-33e80d0b-d945-4ba2-878a-fe40efd096dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQ3NjAsIm5iZiI6MTcwNTYzNDQ2MCwicGF0aCI6Ii8xMDI1MDY2MTgvMjk3Njg3NTU4LTMzZTgwZDBiLWQ5NDUtNGJhMi04NzhhLWZlNDBlZmQwOTZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMzIxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2I0YzEyYmY0ZjcwMDRiMTNjOTU3ZmZlY2UyMDFlZGNhMTM0MDQ5MzVjNDhmMGY1ZmUyMzc3MmYwYjQ5MzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UV3IWgZkzU9Xh_4y1u6QACBFhJ4vToqxLkkiJNQBQUA) @yutingzhao1991

什么原因导致的这个差异？是在 windows 下才有这个问题吗？

**Comment by beilunyang** [comment]
尝试升级下Node版本试试
如：v20.10.0或更新版本 @shanchuan1

**Comment by GoodbyeMyself** [comment]
我发现 回退一个小版本 "@ant-design/web3-wagmi": "^2.3.0"  就正常了

**Comment by yutingzhao1991** [comment]
我这边用 https://github.com/ant-design/ant-design-web3-demo 这个更新 node_modules 之后可以复现这个问题。

初步排查是在 nextjs 中项目构建的时候 `@tanstack/react-query` 引入了多个版本，导致 React 的 context 有问题。

有一个临时解决方案是在项目中单独安装一下 `@tanstack/react-query` 依赖，`pnpm i @tanstack/react-query` 可以解决这个问题。

具体怎么更好的解决要再研究下，相关代码在 https://github.com/ant-design/ant-design-web3/blob/main/packages/wagmi/src/wagmi-provider/index.tsx#L43

**Comment by yutingzhao1991** [comment]
Solution: Install the peerDependencies dependency @tanstack/react-query in the project.
