### ISSUE TITLE
remix use ant-design-web3 Error

### ISSUE THREAD

**Issue by lulongwen** [ant-design/ant-design-web3#519]
remix@2.5.1  use web3 ERROR

`import { NFTCard } from "@ant-design/web3";
         ^^^^^^^
SyntaxError: Named export 'NFTCard' not found. The requested module '@ant-design/web3' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@ant-design/web3';
const { NFTCard } = pkg;`

## remix _index.tsx

import React from 'react';
import {  Button } from 'antd';
import * as antdIcons from '@ant-design/icons';
import { NFTCard } from '@ant-design/web3';
import { BitcoinCircleColorful } from '@ant-design/web3-icons';

import { Layout } from '~/layouts'

const { FormOutlined } = antdIcons

const Home: React.FC = () => {

  return (
    <Layout>
      <Button type='primary'>提交</Button>
      <FormOutlined />
      <BitcoinCircleColorful />
      <NFTCard
        name="My NFT"
        tokenId={16}
        price={{
          value: 1230000000000000000n,
        }}
        like={{
          totalLikes: 1600,
        }}
        description="This is description"
        showAction
        footer="This is footer"
        image="https://api.our-metaverse.xyz/ourms/6_pnghash_0cecc6d080015b34f60bdd253081f36e277ce20ceaf7a6340de3b06d2defad6a_26958469.webp"
      />
    </Layout>
  );
};

export default Home;

## remix.config.js
Invalid reference nextjs configuration

`export default {
  appDirectory: "app",
  tailwind: true,
  postcss: true,
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    // "rc-util",
    // "rc-pagination",
    // "rc-picker",
    // "@ant-design/icons",
    // "@ant-design/web3",
    "@ant-design/web3-icons"
  ],
  // serverModuleFormat: 'esm',
  future: {},
  browserNodeBuiltinsPolyfill: {
    modules: {
      path: true,
    }
  },
}`

**Comment by lulongwen** [comment]
![remix](https://github.com/ant-design/ant-design-web3/assets/13853193/4c60b16e-6265-4c2c-80c6-66d235bdb47c)
remix _index.tsx

**Comment by yutingzhao1991** [comment]
I will take a look at this issue.

**Comment by lulongwen** [comment]
这是来自卢珑文的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yutingzhao1991** [comment]
Doc about use Ant Design Web3 with Remix https://web3.ant.design/guide/quick-start#use-in-remix
