### ISSUE TITLE
NFTCard Displayed images that should not be displayed after switch chain

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#539]
https://github.com/ant-design/ant-design-web3/assets/1061968/c5893795-e6dc-4417-b767-bcb74826fbe7

Reproduction project: https://github.com/yutingzhao1991/fundamental-dapp-demo

Expected result: After switching to test network chain, NFTCard no longer displays NFTs on mainnet

**Comment by yutingzhao1991** [comment]
should display a error image like this:

![image](https://github.com/ant-design/ant-design-web3/assets/1061968/e6e1758e-d764-4533-a90d-d6064ccabb4d)

**Comment by shanchuan1** [comment]
i can carry

**Comment by shanchuan1** [comment]
> should display a error image like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1061968/299522694-e6e1758e-d764-4533-a90d-d6064ccabb4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjM5ODgsIm5iZiI6MTcwNjI2MzY4OCwicGF0aCI6Ii8xMDYxOTY4LzI5OTUyMjY5NC1lNmUxNzU4ZS1kNzY0LTQ1MzMtYTkwZC1kNjA2NGNjYWJiNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMTAwODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M4MmE1OGYzYmM0MjJhOGEwOGFiOTJjMGM1OTI1ODgyMWY3NDNkNGU4MGExNzdlNDA1ZGFiYmJhZjI4NGMwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3cqIsjROt4E3AosTgrHoDAzQsEFGt-sF7mDSz0di_9k)

应该是整个card不展示，还是仅次于image
同时似乎chain与image并没有直接关联

**Comment by yutingzhao1991** [comment]
> > should display a error image like this:
> > ![image](https://private-user-images.githubusercontent.com/1061968/299522694-e6e1758e-d764-4533-a90d-d6064ccabb4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjM5ODgsIm5iZiI6MTcwNjI2MzY4OCwicGF0aCI6Ii8xMDYxOTY4LzI5OTUyMjY5NC1lNmUxNzU4ZS1kNzY0LTQ1MzMtYTkwZC1kNjA2NGNjYWJiNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMTAwODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M4MmE1OGYzYmM0MjJhOGEwOGFiOTJjMGM1OTI1ODgyMWY3NDNkNGU4MGExNzdlNDA1ZGFiYmJhZjI4NGMwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3cqIsjROt4E3AosTgrHoDAzQsEFGt-sF7mDSz0di_9k)
> 
> 应该是整个card不展示，还是仅次于image 同时似乎chain与image并没有直接关联

整个 card 不展示不好。应该就是要展示一个请求失败状态。

chain 和 image 没有直接关联，但是 requestNFTMetadata 和 chain 有关联，切换链之后用 requestNFTMetadata 还是用原来的 NFT 地址和 token 请求 metadata 就会出错。
