### ISSUE TITLE
improve ConnectButton profile modal style

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#551]
![image](https://github.com/ant-design/ant-design-web3/assets/1061968/3a73485c-9aa8-4057-8d72-b14a46521f00)

按照最新的设计稿检查优化细节实现：https://www.figma.com/file/uA5FgofzOVulGceri7SGpW/web3%E6%96%B0%E8%AE%BE%E8%AE%A1%E7%A8%BF?type=design&node-id=0%3A6995&mode=design&t=1Cz6HQy8hDJPdGIY-1

**Comment by NoahStepheno** [comment]
我想做这个功能，但figma中的字体 PingFangSC 无法展示。能提供一下字体么？我系统里有 PingFangSC-Regular 等，没有不带 weight 的。

![截屏2024-08-09 00 30 35](https://github.com/user-attachments/assets/26a96ff0-296f-4e0a-af3f-b03b13978f89)

**Comment by yutingzhao1991** [comment]
@NoahStepheno 看一下方不方便加下我们的钉钉群：

<img width="413" alt="image" src="https://github.com/user-attachments/assets/c628e7f6-9089-4935-a6ed-1d1d3c15e203">

这个 issue 涉及到的调整需要在和设计同学对一下。我给设计同学说一下吧，让他帮忙整理下需要修改的具体内容。

**Comment by NoahStepheno** [comment]
ok

**Comment by yutingzhao1991** [comment]
<img width="1691" alt="image" src="https://github.com/user-attachments/assets/724b106d-e6ad-4daa-92bf-c73c3d6ee507">

@NoahStepheno 和设计师那边确认了，目前要改的只有这一个问题
