### ISSUE TITLE
Solana NFTCard demo not work

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#563]
https://web3.ant.design/zh-CN/components/solana#%E6%9B%B4%E5%A4%9A%E7%BB%84%E4%BB%B6

![image](https://github.com/ant-design/ant-design-web3/assets/1061968/82cb4ea5-8029-4d12-9a36-d2ada6247111)

**Comment by yutingzhao1991** [comment]
@gin-lsl 这个之前你好像说过，是什么原因来着？

**Comment by gin-lsl** [comment]
获取 nft 信息要配置一个 apikey 才行

**Comment by gin-lsl** [comment]
需要在 SolanaWeb3ConfigProvider 的 rpcProvider 配置一下

**Comment by yutingzhao1991** [comment]
> 获取 nft 信息要配置一个 apikey 才行

demo 里面配置一个？应该有免费的吧？类似 https://github.com/ant-design/ant-design-web3/blob/main/.dumirc.ts#L104

**Comment by gin-lsl** [comment]
嗯对，我之前在 helius 注册了一个，作为官网用，credits 量应该是够了的。我搞一下。
