### ISSUE TITLE
ConnectModal SVG Icons show incorrectly

### ISSUE THREAD

**Issue by LCJove** [ant-design/ant-design-web3#581]
steps：
1. open Basic Usage Modal, route to get MetaMask
2. close current modal
3. open another Modal, route to get MetaMask to
4. the chrome icon miss a part of  style

![image](https://github.com/ant-design/ant-design-web3/assets/31850902/23be56cd-e216-4be7-afb5-6c9339902dc1)

**Comment by LCJove** [comment]
目前看来是只有使用了defs来设置fill颜色的时候会导致样式缺失；
另外把metamask 的icon和chrome的icon换一下，也是能正常显示

**Comment by yutingzhao1991** [comment]
> 目前看来是只有使用了defs来设置fill颜色的时候会导致样式缺失； 另外把metamask 的icon和chrome的icon换一下，也是能正常显示

看看是不是和 https://github.com/ant-design/ant-design-web3/issues/310 这个问题类似

**Comment by LCJove** [comment]
> > 目前看来是只有使用了defs来设置fill颜色的时候会导致样式缺失； 另外把metamask 的icon和chrome的icon换一下，也是能正常显示
> 
> 看看是不是和 #310 这个问题类似

是类似的，多个不同svg里面的defs的id一样的话，有可能出现问题

**Comment by LCJove** [comment]
调研下来，这个问题是比较常见的，思路有这么一些：
1. 运行时，给每个svg实例里的id添加uniqId。
2. 将defs的内容写成内联的形式，即删除掉defs。

1的方式需要对AntdIcon做变动。
2的方式，渐变色不好支持内联的形式，这部份的icon可能没有办法做

**Comment by LCJove** [comment]
> > > 目前看来是只有使用了defs来设置fill颜色的时候会导致样式缺失； 另外把metamask 的icon和chrome的icon换一下，也是能正常显示
> > 
> > 
> > 看看是不是和 #310 这个问题类似
> 
> 是类似的，多个不同svg里面的defs的id一样的话，有可能出现问题

一个触发的条件是先展示的icon的display属性变成none（modal被隐藏），可以参考这个
https://codesandbox.io/p/sandbox/svgbug-2ckdcx?file=%2Fsrc%2FApp.tsx

**Comment by gin-lsl** [comment]
这个问题是因为 chrome 的图标，在一个页面上用了多次，然后最前面的那个，被隐藏了的原因是吗？

**Comment by jeasonstudio** [comment]
cc @yutingzhao1991
