### ISSUE TITLE
Support OKX X1

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#600]
https://www.okx.com/cn/x1

新的以太坊 L2，感觉可以支持一下

**Comment by jeasonstudio** [comment]
看了下 X1 的[文档](https://www.okx.com/cn/x1/docs/developer/build-on-x1/quickstart)，应该加一个 icon 和 chain 配置就可以了，ZK-L2 特殊的部分我们都不涉及。
