### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#611]
![image](https://github.com/ant-design/ant-design-web3/assets/1061968/fca4c00f-e933-49eb-9634-420b01a574cb)

加一个一句话描述，这样方便大家快速理解，看看统一叫什么好。

**Comment by jeasonstudio** [comment]
之前那次分享的时候写了一句「Make dapps easier to build」，可以考虑下: https://slides.com/jeasoneth/build-with-zan#/7

另外看了下 antd 的，也比较白话，分别是：
* 助力设计开发者「更灵活」地搭建出「更美」的产品，让用户「快乐工作」～
* Help designers/developers building beautiful products more flexible and working with happiness

**Comment by jeasonstudio** [comment]
![image](https://github.com/ant-design/ant-design-web3/assets/17971291/403f576e-a8a7-44a6-bc4b-5cfccf19c00a)

**Comment by jeasonstudio** [comment]
Awesome react components for building dapps easier.
