### ISSUE TITLE
WalletConnect's text error

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#652]
<img width="969" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/0a85d6bc-e85d-425a-9505-51c8b205e9a0">

WalletConnect 并不是一个 App，是一种协议，文案不对。

可以结合 https://github.com/ant-design/ant-design-web3/issues/614#issue-2172826054 这里的想法：

<img width="880" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/3231b000-0f00-48aa-afd0-8fb9b7f6c644">

协议的情况做下单独的处理。

**Comment by LCJove** [comment]
这个是不是已经处理过了

**Comment by yutingzhao1991** [comment]
嗯 对的
