### ISSUE TITLE
ConnectModal UI Detail Issues Feedback

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#653]
看了一下 ConnectModal，反馈一些细节， @wenqing993 @LCJove  看看要不要改：

1 Modal 的高度可能会变化，看看是不是尽量避免这样的变化
<img width="987" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/84f72b56-5420-490d-a563-391b40d18e92">

2 普通模式下获取钱包的按钮会不会太明显了，喧宾夺主，通常来说用户进来应该是优先要点左侧钱包

<img width="893" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/b5af41f3-44fc-4c23-bd6c-2ee3b047e3a4">

简单模式下就挺好，或者以后就推荐简单模式：
<img width="493" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/a82dbeba-0b3b-4859-8cb4-9eae50e0f3ab">

3 简单模式下文案会被切断，滚动之后可以展示完整，不过这个感觉也还好，可以和问题 1 一起看看。实在不行精简下文案，尽量首屏可以展示完整
<img width="555" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/cf507ff6-23ab-462d-8cc1-87b8df892fca">

4 hover 钱包的时候看看要不要高亮对应操作的按钮，比如下面这种情况，点击整个钱包区域的时候其实就是唤起插件，是不是可以在 cover 的时候激活插件按钮，这样用户会有一个预期：
<img width="906" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/3c5f805d-7180-48c0-b01b-9aa97f5ced65">

类似：
<img width="432" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/348a1404-320f-4cb3-ac7f-473e6742814c">
同理，二维码的时候也一样：
<img width="397" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/12dc9987-0acf-4c26-8ce8-178d7b4d4278">

5 一个二维码都没有的时候是不是可以整体靠右，避免出现这样的空白：
<img width="907" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/9cef4e33-53cc-4c0a-9c02-81b3babd563a">
<img width="914" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/10b1687a-3311-4391-aa2a-3d25912e6bc9">

**Comment by yutingzhao1991** [comment]
钱包名字要避免这行，这种太长的可以阶段改为 `Coinbase Wal...` 这样
<img width="459" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/c339c26a-5122-4b65-a9a7-845500dbef9e">

**Comment by kiner-tang** [comment]
> 钱包名字要避免折行，这种太长的可以阶段改为 `Coinbase Wal...` 这样 <img alt="image" width="459" src="https://private-user-images.githubusercontent.com/1061968/316371927-c339c26a-5122-4b65-a9a7-845500dbef9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzUxODgsIm5iZiI6MTcxMTMzNDg4OCwicGF0aCI6Ii8xMDYxOTY4LzMxNjM3MTkyNy1jMzM5YzI2YS01MTIyLTRiNjUtYTlhNy04NDU1MDBkYmVmOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMDI0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhkYWEzYmM4ZTRiZDZlOTZiNGNmNjA3OGY3MTI0NGQxOWVkNTAyOTJiNDczZjZjZTA2Y2U3YmJhZjMwZTRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wf1SaQFj1pw15HcF3k5Qp_dOcDTWmIAtzzyfCBbwJJ0">

截断后主要要加上 tooltip 展示完整名称。

**Comment by yutingzhao1991** [comment]
> > 钱包名字要避免折行，这种太长的可以阶段改为 `Coinbase Wal...` 这样 <img alt="image" width="459" src="https://private-user-images.githubusercontent.com/1061968/316371927-c339c26a-5122-4b65-a9a7-845500dbef9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzUxODgsIm5iZiI6MTcxMTMzNDg4OCwicGF0aCI6Ii8xMDYxOTY4LzMxNjM3MTkyNy1jMzM5YzI2YS01MTIyLTRiNjUtYTlhNy04NDU1MDBkYmVmOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMDI0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhkYWEzYmM4ZTRiZDZlOTZiNGNmNjA3OGY3MTI0NGQxOWVkNTAyOTJiNDczZjZjZTA2Y2U3YmJhZjMwZTRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wf1SaQFj1pw15HcF3k5Qp_dOcDTWmIAtzzyfCBbwJJ0">
> 
> 截断后主要要加上 tooltip 展示完整名称。

嗯，感觉加上个 `title` 属性就好了，干扰小一点。

**Comment by jeasonstudio** [comment]
1. 直接去掉 get wallet
2. 按钮 type 

![screenshot-Yws8aLHS@2x](https://github.com/ant-design/ant-design-web3/assets/17971291/cbfb215f-8e5d-47f6-a435-bf441644c26f)

**Comment by yutingzhao1991** [comment]
<img width="1055" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/9f2373f7-fff8-48cb-95a7-4bfb2be1377e">

这里我记得设计稿好像有调整。

**Comment by yutingzhao1991** [comment]
<img width="911" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/9f9c303d-e4c8-4d47-a3e7-def4a15a6b6f">

这里的按钮样式好像有点透明度，这个应该不符合预期，应该是没有这个透明度才对
