### ISSUE TITLE
[Bug] ConnectModal QRCode overflow

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#679]
## What happens?

窗口比较小的时候二维码可能会溢出，应该保障尽量的适应屏幕宽度：

<img width="807" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/48acce45-3364-4ec5-9f91-89f7f8fbc873">

<img width="417" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/a6cf2027-dd1d-4713-bee0-7ef8005ce5c7">

## How To Reproduce

Open https://web3.ant.design/~demos/connect-modal-demo-basic
Open WalletConnect QRcode
resize window width

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by thinkasany** [comment]
试了一下用 '100%' 应该可以解决， 我先去隔壁蹭个pr， 不然这边代码提示是红的。

![20240322150028_rec_](https://github.com/ant-design/ant-design-web3/assets/117748716/311bfa96-bd80-459f-9862-9c80aef6ce20)
![image](https://github.com/ant-design/ant-design-web3/assets/117748716/80c809f5-d959-47f1-a871-159b9b142bdb)
![image](https://github.com/ant-design/ant-design-web3/assets/117748716/0011f21e-756f-4bdd-bf64-6532afe3ee18)

**Comment by thinkasany** [comment]
可能还得在等一版本，目前这版的antd qrcode只是把style的width透到了div的style中，svg的witdth还得做个合并，我再去沟通沟通。

<img width="1438" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/117748716/26bd14ee-15d0-42d8-84da-67fe8efc1bc4">

**Comment by thinkasany** [comment]
wait for https://github.com/ant-design/ant-design/pull/48194
