### ISSUE TITLE
[Bug] global is not defined

### ISSUE THREAD

**Issue by erdezhuang** [ant-design/ant-design-web3#693]
当使用模板:https://github.com/wtchnm/Vitamin 安装ant-design/web3-solana 时配好provider 会报

![image](https://github.com/ant-design/ant-design-web3/assets/12458415/1206cebf-f6fa-432d-84dd-72147e8a9d6f)
![image](https://github.com/ant-design/ant-design-web3/assets/12458415/e06b8df1-24f8-4d33-a70b-854cbd77569e)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Vite 5.0.13**:
- **react 18.2.0 **:
- **@ant-design/web3 1.9.0**:
-  **@ant-design/web3-solana 1.0.1**:

**Comment by AmAzing129** [comment]
It seems like a Vite issue. Maybe you can search for solutions in vite community.

**Comment by jeasonstudio** [comment]
`global` 是 nodejs 的全局变量，在浏览器环境会报未定义错误，在 vite 环境中使用 `ant-design-web3` 时可以尝试引入适当的 nodejs polyfill，比如：https://www.npmjs.com/package/vite-plugin-node-polyfills

```js
// vite.config.ts
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [
    nodePolyfills(),
  ],
})
```

我们会在下个版本中考虑更好的兼容 vite
