### ISSUE TITLE
[Bug] Official Website Document UI anomaly

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#700]
## What happens?

<img width="346" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/f261364d-1985-4e05-ab37-f7e554a7dce9">

## How To Reproduce

1. open https://web3.ant.design/
1. Click components
2. Click logo back to home

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by TheKonka** [comment]
Same problem. But don't know why it works fine when I clone the code and run the website locally.

**Comment by thinkasany** [comment]
看了一下是 import 'antd/es/style/reset.css'; 引入了 h1 {margin-bottom: 0.5em; } 从而导致污染全局样式。

**Comment by kiner-tang** [comment]
![image](https://github.com/ant-design/ant-design-web3/assets/10286961/88e6f8aa-6048-4f44-8588-a957878480bc)
![image](https://github.com/ant-design/ant-design-web3/assets/10286961/69620bc5-b3c2-43d0-9ded-cf529dc936d4)
twitter 的按钮也没有展示，也需要一起看看

**Comment by thinkasany** [comment]
记录一下排查思路，佬们可以指点一下，但是也有一个比较迷惑的点就像上面兄弟说到的，本地无法复现，确实我也无法复现，最后是通过express.static加载打包的dist文件去检查修复情况的。

![image](https://github.com/ant-design/ant-design-web3/assets/117748716/1f50d930-8e43-4501-8d01-3970c5b58cd5)


似乎reset.css 就容易导致这样子的问题，后续有需求需要reset的时候可以考虑看看是不是用App组件还是什么的，需要特意留意下可能存在的样式污染的情况。
<img width="1222" alt="Pasted Graphic 3" src="https://github.com/ant-design/ant-design-web3/assets/117748716/a21a3c9b-eede-4987-83a4-5a7740e858e5">

**Comment by eeezgame** [comment]
左侧logo把容器撑高了
![1711511012266](https://github.com/ant-design/ant-design-web3/assets/63237008/216ad954-6ade-4ba2-88c8-258b7fc818da)
此处少写了px后缀
![image](https://github.com/ant-design/ant-design-web3/assets/63237008/abe04e6b-7e13-464a-b702-2a6af3e846b4)

**Comment by jeasonstudio** [comment]
> 左侧logo把容器撑高了
> 
> ![1711511012266](https://private-user-images.githubusercontent.com/63237008/317116678-216ad954-6ade-4ba2-88c8-258b7fc818da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTE5NzAsIm5iZiI6MTcxMTUxMTY3MCwicGF0aCI6Ii82MzIzNzAwOC8zMTcxMTY2NzgtMjE2YWQ5NTQtNmFkZS00YmEyLTg4YzgtMjU4YjdmYzgxOGRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzNTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MzlmZGYzNTVkZTAxNWU0YTE0YmIwMzcxMTgzZjkyNmFhMjIxN2E4MGEyZDZmMTEyYmI0ZjlmZDk5ZDk5NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lOMcdJC8r9asAJbXDctROZOZVmkNERYLgvVdfPrfKiY)
> 
> 此处少写了px后缀 https://github1s.com/KuangPF/dumi-theme-antd/blob/main/src/slots/Header/Logo.tsx#L68
> 
> ![image](https://private-user-images.githubusercontent.com/63237008/317116929-abe04e6b-7e13-464a-b702-2a6af3e846b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTE5NzAsIm5iZiI6MTcxMTUxMTY3MCwicGF0aCI6Ii82MzIzNzAwOC8zMTcxMTY5MjktYWJlMDRlNmItN2UxMy00NjRhLWI3MDItMmE2YWYzZTg0NmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzNTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMjRmODRjNWJlNjliMGE5NmViZjlhZTA0NjhmZjhjMGI0MzI3NGNlODgyMGUyOTIyYjI3MTA4ZGZjZTkyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K6p_cnqpSa2MuFEok4wxzqHHpiijz0-v4d_JggdMnZ4)

👍，刚刚顺手把这个问题修复了，发了个版本 `dumi-theme-antd-web3@0.3.13`，同时也 pr 到了原项目 (https://github.com/KuangPF/dumi-theme-antd/pull/29)

如果你感兴趣可以提一个 pr 更新下本项目使用的 `dumi-theme-antd-web3` 版本来解决这个问题～

**Comment by thinkasany** [comment]
#722 @eeezgame  感兴趣可以提一个 pr 更新下本项目使用的 dumi-theme-antd-web3 版本来解决这个问题～

**Comment by eeezgame** [comment]
> #722 @eeezgame 感兴趣可以提一个 pr 更新下本项目使用的 dumi-theme-antd-web3 版本来解决这个问题～

好的

**Comment by kiner-tang** [comment]
> > #722 @eeezgame 感兴趣可以提一个 pr 更新下本项目使用的 dumi-theme-antd-web3 版本来解决这个问题～
> 
> 好的

@eeezgame 这边刚好在改其他问题，顺便把这个问题也改了，如果感兴趣的话，可以看看其他 issue,欢迎 pr。
