### ISSUE TITLE
docs: img add default alt

### ISSUE THREAD

**Issue by chenjixue** [ant-design/ant-design-web3#705]
## What happens?

中文文档顶部log图片未加载没有alt描述信息

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![1711443075484](https://github.com/ant-design/ant-design-web3/assets/57701429/d4f86765-ff82-42ea-9579-0d62b5ae9f72)
## Context

- **Ant Design Web3 Version**:2.0.0

**Comment by thinkasany** [comment]
You can add a specific description, thanks for your contribution!
可以加上具体描述，感谢你的贡献!

**Comment by kiner-tang** [comment]
可以全局搜一下文档中没有加 alt 的 img，顺带都加上

**Comment by thinkasany** [comment]
为了避免恶意蹭pr，我们不会处理单个alt了，要么一次性都改了，要么就直接close 了。
