### ISSUE TITLE
[Bug] website logo height overflow

### ISSUE THREAD

**Issue by thinkasany** [ant-design/ant-design-web3#722]
## What happens?
#700 
左侧logo把容器撑高了
![image](https://github.com/ant-design/ant-design-web3/assets/117748716/29fa9abd-200c-427e-bf48-5d094ad9b45d)

dumi-theme-antd-web3@0.3.13 中修复了这个bug，可以通过升级去解决

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by thinkasany** [comment]
@eeezgame 小伙伴发现的问题，可以看看他有没有空处理，先挂起。

**Comment by kiner-tang** [comment]
我这边刚好需要改 dumi-theme-antd-web3，我来身边升一级一下吧

**Comment by thinkasany** [comment]
> 我这边刚好需要改 dumi-theme-antd-web3，我来身边升一级一下吧

要不要问一下他，原本设想尽量邀请新的小伙伴加入开源大家庭。

![image](https://github.com/ant-design/ant-design-web3/assets/117748716/62d33267-4848-4cc2-9667-550614f376a7)
