### ISSUE TITLE
[Bug] useAccount 获取不到当前已连接的用户

### ISSUE THREAD

**Issue by iwindx** [ant-design/ant-design-web3#727]
我理解在@ant-design/web3 维护了这些 hooks 的状态， 只要连接了钱包， 就能获取到对应状态吧

<img width="740" alt="WechatIMG134" src="https://github.com/ant-design/ant-design-web3/assets/16376649/4be54ab7-b220-4791-9f7c-185768847d26">
<img width="1286" alt="WechatIMG135" src="https://github.com/ant-design/ant-design-web3/assets/16376649/81d8f4f8-2f1a-40aa-bab1-eb5c2ae016af">

**Comment by jeasonstudio** [comment]
上述 react-hooks 都需要被 `WagmiWeb3ConfigProvider` 包裹后使用

**Comment by yutingzhao1991** [comment]
`WagmiWeb3ConfigProvider` 包在最外面就行了，你的 useAccount 不在这里面，所以获取不到上下文。
