### ISSUE TITLE
[BUG] site: The menu display of the official website in mobile mode is abnormal

### ISSUE THREAD

**Issue by kiner-tang** [ant-design/ant-design-web3#745]
## What happens?

<img width="730" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/10286961/7f0ebf31-771c-43b1-91ea-9fb1a205aa3b">

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by yutingzhao1991** [comment]
related https://github.com/ant-design/ant-design-web3/issues/612
