### ISSUE TITLE
[Feature Request] connect modal optimize

### ISSUE THREAD

**Issue by YeezoGao** [ant-design/ant-design-web3#787]
## Background
1. 初始页面的get wallet过于突出，需要弱化
2. 在连接钱包的时候modal添加loading的状态

![image](https://github.com/ant-design/ant-design-web3/assets/31850902/4091ce12-41fc-4143-a7c1-66581c7997ce)

## Proposal

1. 删除get wallet 按钮，以及对应的路由页面。该部分的内容有其他的方式可以触达
2. 有两个想法，一个是简单添加一个loading的参数，让开发这自己控制是否loading；另一个是组件做，但是需要获取到用户自己设计的连接方法，不一定可以获取到，大家有什么想法吗

**Comment by yutingzhao1991** [comment]
第二个这个就组件直接做就行，加一个 loading 页面，唤起插件后不关闭弹窗，而是显示 loading，直到连接成功。

我记得之前设计稿有的，只是说稿子要优化一下，类似这样：
<img width="507" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/455a58fc-861e-457a-a1e8-1815f0bc1bb3">

**Comment by yutingzhao1991** [comment]
<img width="575" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/f65d0cd1-0c35-4685-820c-39169c138b0e">

还有这个按钮感觉有点不太协调，没对齐。之前好像文卿说过去掉按钮的形态，可以和他确认下。
