### ISSUE TITLE
[Feature Request] What's the next on bitcoin

### ISSUE THREAD

**Issue by AmAzing129** [ant-design/ant-design-web3#800]
## Background

比特币 [Runes](https://docs.ordinals.com/runes/specification.html) 协议将在区块 840000 激活。目前有很多钱包与平台提供了代币 etch 等服务。如果可以更新 API，会引流部分新 dApp 使用 ant-design-web3.

The Bitcoin [Runes](https://docs.ordinals.com/runes/specification.html) protocol will be activated at block 840,000. Currently, many wallets and platforms offer services such as etching token. Updating the API could attract new dApps to use ant-design-web3.

## Proposal

参考 [Xverse](https://docs.xverse.app/sats-connect/bitcoin-methods/mint-runes) 提供的 API，封装统一接口暴露出去。

Referencing the API provided by [Xverse](https://docs.xverse.app/sats-connect/bitcoin-methods/mint-runes), wrap and expose it.

**Comment by ONLY-yours** [comment]
support，建议 NFTCard 直接变体几个 Card：Runes、Ordinals wip，一并支持

**Comment by AmAzing129** [comment]
比特币生态目前处于探索期，本 issue 长期开放，讨论下开发者究竟需要什么。目前待做：
- [ ] 支持测试网
- [ ] Ordinals Card 组件
- [ ] 支持 OKX 钱包

**Comment by yutingzhao1991** [comment]
Ordinals Card 组件这个可以直接用现在的 NFTCard 吗？

**Comment by AmAzing129** [comment]
> Ordinals Card 组件这个可以直接用现在的 NFTCard 吗？

基于当前做一些改造，样式复用，把图片获取逻辑变成解析 Ordinals 图片
