### ISSUE TITLE
单测覆盖率不足100%

### ISSUE THREAD

**Issue by thinkasany** [ant-design/ant-design-web3#830]
目前覆盖率变成99.97了，初步排查好像是因为这个pr https://github.com/ant-design/ant-design-web3/pull/806/files，移除了
```onClick={() => updatePanelRoute('getWallet')}``` 导致的。

不确定下面这段代码还有用不，现在好像不存在更新panelRoute为‘getWallet’的情况。
![image](https://github.com/ant-design/ant-design-web3/assets/117748716/16de9217-4fba-4218-b725-103baf3990c8)

![image](https://github.com/ant-design/ant-design-web3/assets/117748716/b4dbd232-c339-48e8-9349-6d409792c5d7)

![image](https://github.com/ant-design/ant-design-web3/assets/117748716/7c80aadd-da68-4c6c-83d1-259745f107bd)

可通过[codecov](https://app.codecov.io/gh/ant-design/ant-design-web3/blob/main/packages%2Fweb3%2Fsrc%2Fconnect-modal%2Fcomponents%2FModalPanel.tsx)查看覆盖率。

![image](https://github.com/ant-design/ant-design-web3/assets/117748716/43f8ee09-15fc-45bd-919a-5b8277969a95)

![image](https://github.com/ant-design/ant-design-web3/assets/117748716/e7929fba-f4a0-4a8a-b115-cad4a2d70166)

**Comment by yutingzhao1991** [comment]
应该没有 getWallet 这个 pannel 了，可以直接删掉。

**Comment by thinkasany** [comment]
最后0.02未覆盖的地方，在这个pr中移除了使用但是未清除 unused code。https://github.com/ant-design/ant-design-web3/pull/806/files#diff-06f5ec7527662eec01c5d945d09c5344d75141cec3ef8b76ecf20325752f2468

由于先前的代码是kiner哥留下的，辛苦kiner哥先看一下，你可能更清楚这一块，来不及的话后面我再处理，先assign 给你啦 @kiner-tang ～

<img width="468" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/117748716/210c2b00-ed66-4119-ab73-588893b742ec">
