### ISSUE TITLE
[Bug] Module not found: Can't resolve 'fs' when using bitcoin package in next.js

### ISSUE THREAD

**Issue by AmAzing129** [ant-design/ant-design-web3#878]
## What happens?

在 Next.js 中使用 @ant-design/web3-bitcoin 报错

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by AmAzing129** [comment]
- [ ] mempoolJS 使用了 [ws](https://github.com/websockets/ws) 不支持 client
- [ ] window 对象需要做 next.js 适配

**Comment by jeasonstudio** [comment]
`@mempool/mempool.js` 看起来并没有积极维护，我们如果只用了其中几个 get 接口，不如直接改成 fetch 调用，参考 restful api 文档：https://mempool.space/zh/docs/api/rest

**Comment by AmAzing129** [comment]
The same as https://github.com/ant-design/ant-design-web3/issues/880
