### ISSUE TITLE
@ant-design/web3-bitcoin Module not found: Can't resolve 'net'

### ISSUE THREAD

**Issue by dlnuchunge** [ant-design/ant-design-web3#880]
![image](https://github.com/ant-design/ant-design-web3/assets/25683599/fcc5b082-8cf9-4740-a8ea-f45cff002297)

**Comment by AmAzing129** [comment]
The same as https://github.com/ant-design/ant-design-web3/issues/878, will be fixed ASAP.

**Comment by AmAzing129** [comment]
@dlnuchunge fix it in 1.1.0
