### ISSUE TITLE
[Bug]Connecting logo need to adapt base64 img

### ISSUE THREAD

**Issue by gin-lsl** [ant-design/ant-design-web3#896]
## What happens?

正在连接中的钱包 logo 没有适配字符串形式的 icon

![image](https://github.com/ant-design/ant-design-web3/assets/18319675/b0c65d0e-3767-4e72-ad4a-31f4bebe8b88)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by yutingzhao1991** [comment]
感觉是没有读到 
<img width="92" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/68a45e6f-f429-4f53-bebf-5cb0ea8dc4ac">
 这个图片

**Comment by gin-lsl** [comment]
有些自动检测到的钱包，是 base64
