### ISSUE TITLE
ledgerhq/error has some bugs.

### ISSUE THREAD

**Issue by OmAnand857** [ant-design/ant-design-web3#904]
## What happens?
export 'TransportRaceCondition' (imported as 'TransportRaceCondition') was not found in '@ledgerhq/errors' (possible exports: AccountNameRequiredError, AccountNotSupported, AmountRequired, BluetoothRequired, BtcUnmatchedApp, CantOpenDevice, CantScanQRCode, CashAddrNotSupported, ClaimRewardsFeesWarning, CurrencyNotSupported, DBNotReset, DBWrongPassword, DeviceAppVerifyNotSupported, DeviceExtractOnboardingStateError, DeviceGenuineSocketEarlyClose, DeviceHalted, DeviceInOSUExpected, DeviceNameInvalid, DeviceNeedsRestart, DeviceNotGenuineError, DeviceOnDashboardExpected, DeviceOnDashboardUnexpected, DeviceOnboardingStatePollingError, DeviceShouldStayInApp, DeviceSocketFail, DeviceSocketNoBulkStatus, DisabledTransactionBroadcastError, DisconnectedDevice, DisconnectedDeviceDuringOperation, DustLimit, ETHAddressNonEIP, EnpointConfigError, EthAppPleaseEnableContractData, ExpertModeRequired, FeeEstimationFailed, FeeNotLoaded, FeeNotLoadedSwap, FeeRequired, FeeTooHigh, FirmwareNotRecognized, FirmwareOrAppUpdateRequired, GasLessThanEstimate, GenuineCheckFailed, HardResetFail, HwTransportError, HwTransportErrorType, InvalidAddress, InvalidAddressBecauseDestinationIsAlsoSource, InvalidNonce, InvalidXRPTag, LanguageNotFound, LatestMCUInstalledError, LedgerAPI4xx, LedgerAPI5xx, LedgerAPIError, LedgerAPIErrorWithMessage, LedgerAPINotAvailable, LockedDeviceError, MCUNotGenuineToDashboard, ManagerAppAlreadyInstalledError, ManagerAppDepInstallRequired, ManagerAppDepUninstallRequired, ManagerAppRelyOnBTCError, ManagerDeviceLockedError, ManagerFirmwareNotEnoughSpaceError, ManagerNotEnoughSpaceError, ManagerUninstallBTCDep, MaxFeeTooLow, NetworkDown, NetworkError, NoAccessToCamera, NoAddressesFound, NoDBPathGiven, NotEnoughBalance, NotEnoughBalanceBecauseDestinationNotCreated, NotEnoughBalanceInParentAccount, NotEnoughBalanceToDelegate, NotEnoughGas, NotEnoughGasSwap, NotEnoughSpendableBalance, NotSupportedLegacyAddress, OpReturnDataSizeLimit, PairingFailed, PasswordIncorrectError, PasswordsDontMatchError, PeerRemovedPairing, PendingOperation, PriorityFeeHigherThanMaxFee, PriorityFeeTooHigh, PriorityFeeTooLow, RecipientRequired, RecommendSubAccountsToEmpty, RecommendUndelegation, ReplacementTransactionUnderpriced, SequenceNumberError, StatusCodes, SyncError, TimeoutTagged, TransactionHasBeenValidatedError, TransportError, TransportExchangeTimeoutError, TransportInterfaceNotAvailable, TransportOpenUserCancelled, TransportPendingOperation, TransportStatusError, TransportWebUSBGestureRequired, UnavailableTezosOriginatedAccountReceive, UnavailableTezosOriginatedAccountSend, UnexpectedBootloader, UnknownMCU, UnresponsiveDeviceError, UpdateFetchFileFail, UpdateIncorrectHash, UpdateIncorrectSig, UpdateYourApp, UserRefusedAddress, UserRefusedAllowManager, UserRefusedDeviceNameChange, UserRefusedFirmwareUpdate, UserRefusedOnDevice, WebsocketConnectionError, WebsocketConnectionFailed, WrongAppForCurrency, WrongDeviceForAccount, WrongDeviceForAccountPayout, WrongDeviceForAccountRefund, addCustomErrorDeserializer, createCustomErrorClass, deserializeError, getAltStatusMessage, serializeError)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by gin-lsl** [comment]
Can you try using the latest version of the @ant-design/web3-solana? I removed the module that causing the problem.
