### ISSUE TITLE
[Bug] Get wallet btn overflow

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#918]
## What happens?

自定义 design token 的情况下 get wallet btn 可能会溢出，另外按钮和文字不对齐

<img width="504" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/19dc97ad-340e-4f4b-9054-d3f37e5cf557">

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

可以参考 https://web3.ant.design/guide/theme 这个的 design token

<img width="846" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/e1f88c29-6dc0-46cd-94a8-f6c8264859ac">

## Context

- **Ant Design Web3 Version**:
- **Node Version**:
- **Platform**:

**Comment by yutingzhao1991** [comment]
.ant-web3-connect-modal-body 上面写死了一个高度，要看看怎么调整更好一点。 @LCJove 高度这个逻辑是不是你之前加的，之前是考虑哪些点？看看有没有更好的办法

**Comment by LCJove** [comment]
应该是为了避免内容变化导致modal切换的时候高度会变化，改成minHeight应该会好一点
