### ISSUE TITLE
[Bug] @ant-design/web3-solana在vite项目中报错 Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by qvvvvq** [ant-design/ant-design-web3#938]
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
vite项目中正常使用@ant-design/web3-solana
**Expected behavior** 1. 2.

![image](https://github.com/ant-design/ant-design-web3/assets/138279383/f054a5aa-f771-4de0-a0e0-3806e9a972d3)
![image](https://github.com/ant-design/ant-design-web3/assets/138279383/9cc92066-b162-4549-ab73-8656c6811c4c)
![image](https://github.com/ant-design/ant-design-web3/assets/138279383/3fe1af23-dce5-49fa-8688-02de3677058b)

## Context

- **Ant Design Web3 Version**: 1.13.0
- **Node Version**: v18.16.0
- **Platform**: Chrome

**Comment by gin-lsl** [comment]
You can resolve it line this https://github.com/ant-design/ant-design-web3/issues/693#issuecomment-2017406465
