### ISSUE TITLE
[Bug] 移动端官网中文链接跳转错误

### ISSUE THREAD

**Issue by jrr997** [ant-design/ant-design-web3#968]
## What happens?
https://github.com/ant-design/ant-design-web3/assets/73225408/1ba0f084-bc75-484c-adc3-95c8e83b1fb2

**Comment by jeasonstudio** [comment]
Fixed in https://github.com/jeasonstudio/dumi-theme-antd/commit/828eff46d7a3e64647190fea5921f7cbd1114d5c
