### ISSUE TITLE
[Bug] WalletConnect showQrModal 为 true 时，出现两个弹窗

### ISSUE THREAD

**Issue by jeasonstudio** [ant-design/ant-design-web3#982]
## What happens?

当 showQrModal 配置不为 false 时，会使用 WallectConnect 自带的 [web3modal](https://web3modal.com/) 弹窗，但是我们自己的弹窗不会消失。

![screenshot-2ZczslGv@2x](https://github.com/ant-design/ant-design-web3/assets/17971291/2b6a5db2-bdb5-46fc-9392-3e3b53980f06)

## How To Reproduce

https://web3.ant.design/components/ethereum-cn#%E4%BD%BF%E7%94%A8-web3modal-%E8%BF%9E%E6%8E%A5-walletconnect

**Comment by ONLY-yours** [comment]
我无法从createConfig 配置出来的 wagmi config 里面拿到东西判断 showQrModal 的配置，有点坑，我提一个 pr 上来用 dom 上面的 className 判断，看看大家有没有更好的。

**Comment by yutingzhao1991** [comment]
> 我无法从createConfig 配置出来的 wagmi config 里面拿到东西判断 showQrModal 的配置，有点坑，我提一个 pr 上来用 dom 上面的 className 判断，看看大家有没有更好的。

不需要这样判断，有一个属性 `useWalletConnectOfficialModal` ，用户手动指定就行，只是现在这个属性没生效。

**Comment by yutingzhao1991** [comment]
感觉 https://github.com/ant-design/ant-design-web3/issues/919 这个 issue 可以推进下了，不直接暴露 wagmi 的配置给开发者，这样就不会有这样的问题了，现在开发者需要同时维护 wagmi 和 web3 的配置，两边配置需要匹配，确实容易出错。

**Comment by jeasonstudio** [comment]
> 感觉 #919 这个 issue 可以推进下了，不直接暴露 wagmi 的配置给开发者，这样就不会有这样的问题了，现在开发者需要同时维护 wagmi 和 web3 的配置，两边配置需要匹配，确实容易出错。

正在做重构
