### ISSUE TITLE
Fix polygon icon

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-web3#99]
<img width="833" alt="image" src="https://github.com/ant-design/ant-design-web3/assets/1061968/59f707b3-4acf-41fa-9bc7-aabad33cd129">

**Comment by lesenelir** [comment]
你好。

请教下，我修改了 `/packages/icons/src/svgs/*`  文件夹内的文件，但是我在 `pnpm dev:docs` 后，并不能在 `localhost:8000/components/icons` 本地开发环境看到相关 svg 的热更新。
请问这个正常吗，正常不应该是修改后即能看到修改后的结果，是我打开方式有什么问题吗。。。

**Comment by yutingzhao1991** [comment]
> 你好。
> 
> 请教下，我修改了 `/packages/icons/src/svgs/*` 文件夹内的文件，但是我在 `pnpm dev:docs` 后，并不能在 `localhost:8000/components/icons` 本地开发环境看到相关 svg 的热更新。 请问这个正常吗，正常不应该是修改后即能看到修改后的结果，是我打开方式有什么问题吗。。。

启动另外一个控制台执行下 `pnpm run dev` 应该就好了。

**Comment by yutingzhao1991** [comment]
> 你好。
> 
> 请教下，我修改了 `/packages/icons/src/svgs/*` 文件夹内的文件，但是我在 `pnpm dev:docs` 后，并不能在 `localhost:8000/components/icons` 本地开发环境看到相关 svg 的热更新。 请问这个正常吗，正常不应该是修改后即能看到修改后的结果，是我打开方式有什么问题吗。。。

试了下，好像确实有问题，建了个 issue https://github.com/ant-design/ant-design-web3/issues/120
